apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-bot
  namespace: {{ regexReplaceAll "\\W+" .Chart.Name  "-" }}-{{ .Values.env }}
annotation:
  vault.hashicorp.com/agent-inject: 'true'
  vault.hashicorp.com/role: 'internal-app'
  vault.hashicorp.com/agent-inject-secret-config: 'apps/carrot/prod/bot/main_mnemonic'
  vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "apps/carrot/prod/bot/main_mnemonic" -}}
            export MAIN_MNEMONIC="{{ .Data }}"
          {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ regexReplaceAll "\\W+" .Chart.Name  "-" }}-bot-{{ .Values.env }}-{{ regexReplaceAll "\\W+" .Chart.AppVersion "-" }}
  template:
    metadata:
      labels:
        app: {{ regexReplaceAll "\\W+" .Chart.Name  "-" }}-bot-{{ .Values.env }}-{{ regexReplaceAll "\\W+" .Chart.AppVersion "-" }}
    spec:
      serviceAccountName: internal-app
      containers:
      - name: {{ .Chart.Name }}-bot
        image: 537748208826.dkr.ecr.us-east-1.amazonaws.com/carrot-bot:{{ .Values.bot.version}}
        command:
            ['sh', '-c']
          args:
            ['source /vault/secrets/config && ./entrypoint.sh']
        env:
        - name: RUST_LOG
          value: info
        #- name: MAIN_MNEMONIC
        #  valueFrom:
        #    secretKeyRef:
        #      name: carrot-bot
        #      key: bot-mnemonic
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

