apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-bot
  namespace: {{ regexReplaceAll "\\W+" .Chart.Name  "-" }}-{{ .Values.env }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-bot
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-bot
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'internal-app'
        vault.hashicorp.com/agent-inject-secret-bot: '{{ .Values.bot.mnemonic_path }}'
        vault.hashicorp.com/agent-inject-template-bot: |
          {{`{{- with secret "{{ .Values.bot.mnemonic_path }}" -}}
            export MAIN_MNEMONIC="{{ .Data.data.mnemonic }}"
          {{- end }}`}}
    spec:
      serviceAccountName: internal-app
      containers:
      - name: {{ .Chart.Name }}-bot
        image: 537748208826.dkr.ecr.us-east-1.amazonaws.com/carrot-bot:{{ .Values.bot.version}}
        imagePullPolicy: Always
        env:
        - name: RUST_LOG
          value: info
        ports:
        - containerPort: 8000

