---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-bot-ingress
  namespace: {{ regexReplaceAll "\\W+" .Chart.Name  "_" }}_{{ .Values.env }}_{{ regexReplaceAll "\\W+" .Chart.AppVersion "_" }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/ssl-redirect: "false"
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Chart.Name }}-bot.{{ .Chart.Name }}.abstract.money
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Chart.Name }}-bot
            port:
              number: 80
  tls:
  - hosts:
    - {{ .Chart.Name }}-bot.{{ .Chart.Name }}.abstract.money
    secretName: {{ .Chart.Name }}-bot-cert
