apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-bot
  namespace: {{ regexReplaceAll "\\W+" .Chart.Name  "_" }}_{{ .Values.env }}_{{ regexReplaceAll "\\W+" .Chart.AppVersion "_" }}
spec:
  selector:
    app: {{ .Chart.Name }}-bot
  ports:
  - port: 80
    targetPort: 8000
