apiVersion: apps/v1
kind: Deployment
metadata:
  name: console-{{ .Values.env }}
  namespace: {{ regexReplaceAll "\\W+" .Chart.Name  "-" }}-{{ .Values.env }}
spec:
  selector:
    matchLabels:
      app: console-{{ .Values.env }}
  template:
    metadata:
      labels:
        app: console-{{ .Values.env }}
    spec:
      containers:
      - name: console
        image: "{{ .Values.apps.console.image }}:{{ .Values.apps.console.version }}"
        imagePullPolicy: Always
        env:
        - name: RUST_LOG
          value: info
        - name: SERVER_PORT
          value: "8001"
        ports:
        - containerPort: 8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aether-api-{{ .Values.env }}
  namespace: "{{ regexReplaceAll "\\W+" .Chart.Name  "-" }}-{{ .Values.env }}"
spec:
  selector:
    matchLabels:
      app: aether-api-{{ .Values.env }}
  template:
    metadata:
      labels:
        app: aether-api-{{ .Values.env }}
    spec:
      containers:
        - name: aether-api
          image: "{{ .Values.apps.aether.image }}:{{ .Values.apps.aether.version }}"
          imagePullPolicy: Always
          env:
          - name: RUST_LOG
            value: info
          - name: SERVER_PORT
            value: "8001"
          ports:
          - containerPort: 8001




