{{- $root := . -}}
{{ range $app := .Values.apps }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: c{{ $app.image  }}-{{ $root.Values.env }}
  namespace: {{ regexReplaceAll "\\W+" .Chart.Name  "-" }}-{{ $root.Values.env }}
spec:
  selector:
    matchLabels:
      app: {{ $app.image  }}-{{ $root.Values.env }}
  template:
    metadata:
      labels:
        app: {{ $app.image  }}-{{ $root.Values.env }}
    spec:
      containers:
      - name: {{ $app.image  }}
        image: {{ $app.image  }}:{{ $app.version }}
        imagePullPolicy: Always
        {{ if hasKey $app "env" }}
        env:
        {{ range $env := $app.env }}
        - name: {{ $env.name }}
          value: {{ $env.value }}
          {{ end }}
        {{ end }}
        ports:
        - containerPort: 8001
  
{{ end }}
