{{ range $app := .Values.apps }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console-{{ .Values.env }}
spec:
  selector:
    matchLabels:
      app: console-{{ .Values.env }}
  template:
    metadata:
      labels:
        app: console-{{ .Values.env }}
    spec:
      containers:
      - name: console
        image: {{ $app.image  }}:{{ $app.version }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
  
{{ end }}
