{{- $root := . -}}
{{ range $app := .Values.apps }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $app.name  }}-{{ $.Values.env }}
  namespace: {{ regexReplaceAll "\\W+" $.Chart.Name  "-" }}-{{ $.Values.env }}
spec:
  selector:
    matchLabels:
      app: {{ $app.name  }}-{{ $.Values.env }}
  template:
    metadata:
      labels:
        app: {{ $app.name  }}-{{ $.Values.env }}
    spec:
      containers:
      - name: {{ $app.name  }}
        image: {{ $app.image  }}:{{ $app.version }}
        imagePullPolicy: Always
        {{ if hasKey $app "env" }}
        env:
        {{ range $env := $app.env }}
        - name: {{ $env.name }}
          value: "{{ $env.value }}"
          {{ end }}
        {{ end }}
        ports:
        - containerPort: 8001
  
{{ end }}
