{{ range $app := .Values.apps }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $app.name  }}-{{ $.Values.env }}
  namespace: {{ regexReplaceAll "\\W+" $.Chart.Name  "-" }}-{{ $.Values.env }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/ssl-redirect: "false"
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: {{ $app.name  }}.{{ $.Values.env }}.{{ $.Chart.Name }}.abstract.money
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $app.name  }}-{{ $.Values.env }}
            port:
              number: 80
  tls:
  - hosts:
    - {{ $app.name  }}.{{ $.Values.env }}.{{ $.Chart.Name }}.abstract.money
    secretName: {{ $app.name  }}-cert
{{ end }}
