{{ range $app := .Values.apps }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $app.name  }}-{{ $.Values.env }}
  namespace: {{ regexReplaceAll "\\W+" $.Chart.Name  "-" }}-{{ $.Values.env }}
spec:
  selector:
    app: {{ $app.name  }}-{{ $.Values.env }}
  ports:
  - port: 80
    targetPort: {{ $app.port }}
{{ end }}
