apiVersion: v1
kind: Service
metadata:
  name: console-{{ .Values.env }}
  namespace: {{ regexReplaceAll "\\W+" .Chart.Name  "-" }}-{{ .Values.env }}
spec:
  selector:
    app: console-{{ .Values.env }}
  ports:
  - port: 80
    targetPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: aether-api-{{ .Values.env }}
  namespace: {{ regexReplaceAll "\\W+" .Chart.Name  "-" }}-{{ .Values.env }}
spec:
  selector:
    app: aether-api-{{ .Values.env }}
  ports:
  - port: 80
    targetPort: 8001
