apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aether-prod
  namespace: argocd
spec:
  destination:
    namespace: aether
    server: https://kubernetes.default.svc
  project: aether
  source:
    chart: aether
    helm:
      valueFiles:
        - environments/prod/values.yaml
    repoURL: https://abstractsdk.github.io/deployments/
    targetRevision: 0.x
  syncPolicy:
    automated: {}
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
---

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: aether
  namespace: argocd
spec:
  description: aether API
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - name: in-cluster
      namespace: '*'
      server: https://kubernetes.default.svc
  orphanedResources:
    warn: true
  sourceRepos:
    - https://github.com/AbstractSDK/aether
    - https://github.com/AbstractSDK/deployments
  
