name: apply argocd application 

on:
  push:
    branches: [ main ] 

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:

  apply:
    runs-on: ubuntu-latest  # Adjust OS as needed

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::537748208826:role/github-actions-to-eks
          aws-region: us-east-1
          
      - name: Generate kubeconfig
        run: |
             {
               echo 'KUBE_CONFIG<<EOF'
               aws eks update-kubeconfig --region us-east-1 --name prod-eks-2 --dry-run | base64
               echo EOF
             } >> "$GITHUB_ENV"
      - run: kubectl --context arn:aws:eks:us-east-1:537748208826:cluster/prod-eks-2
      - name: Update kube config
        run: aws eks update-kubeconfig --name prod-eks-2 --region us-east-1
      - run: kubectl config current-context
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ env.KUBE_CONFIG }}
      - run: kubectl get pods --all-namespaces
  
      - run: |
          kubectl apply -f charts/carrot/environments/prod/argo-app.yaml