name: apply argocd application 

on:
  push:
    branches: [ main ] 

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:

  build-and-push:
    runs-on: ubuntu-latest  # Adjust OS as needed

    steps:
      - uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::537748208826:role/github-action
          role-session-name: github-actions-ecr-access-role
          aws-region: us-east-1

      - run: |  
          curl -LO "https://dl.k8s.io/release/v1.25.0/bin/linux/amd64/kubectl"
          chmod +x kubectl
          mv kubectl ~/bin/kubectl

      - run: |
          kubectl apply -f charts/carrot/environments/argo-app.yaml