name: apply argocd application 

on:
  push:
    branches: [ main ] 

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:

  apply:
    runs-on: ubuntu-latest  # Adjust OS as needed

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::537748208826:role/github-actions-to-eks
          aws-region: us-east-1
          
      - name: Generate kubeconfig
        run: |
             {
               echo 'KUBE_CONFIG<<EOF'
               aws eks update-kubeconfig --region us-east-1 --name prod-eks-2 --dry-run | base64
               echo EOF
             } >> "$GITHUB_ENV"
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ env.KUBE_CONFIG }}
      - run:  kubectl config get-contexts
      #- run: aws eks update-kubeconfig --region us-east-1 --name prod-eks-2
      - name: Configure AWS Credentials
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
          echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials

          echo "[default]" > ~/.aws/config
          echo "region = us-east-1" >> ~/.aws/config
      - run:  cat ~/.kube/config
      - run:  cat ~/.aws/credentials
      - run: aws eks list-clusters
      - run: kubectl config view
      #- run: kubectl cluster-info
      - run:  kubectl get pods --server https://90261FA1170C82588E5619262E2226A3.gr7.us-east-1.eks.amazonaws.com
  
      - run: |
          kubectl apply -f charts/carrot/environments/prod/argo-app.yaml
